const ROLLER = 1
const VERTICAL = 2
const VERTICAL_LO_ONLY = 3
const VERTICAL_LO_ONLY_RIGID_PVC = 4
const VENETIAN = 5
const ROLL_EXPRESS = 6

const PRODUCTS = [
    ROLLER,
    VERTICAL,
    VERTICAL_LO_ONLY,
    VERTICAL_LO_ONLY_RIGID_PVC,
    VENETIAN,
    ROLL_EXPRESS
]

export {
    ROLLER,
    VERTICAL,
    VERTICAL_LO_ONLY,
    VERTICAL_LO_ONLY_RIGID_PVC,
    VENETIAN,
    ROLL_EXPRESS,
    PRODUCTS
}
