const ROLLER = ['AED', 'AES', 'BRB', 'CF90-38', 'CF90-50', 'CF90-CRANK1', 'EW', 'INSP240', 'INSPBAT', 'INSPCH', 'PRCR', 'RB', 'RB-LO32', 'RCR', 'RDRS', 'REDR', 'RSL32', 'RSL38', 'RSL50', 'RSL63', 'RSL83', 'S45-ROLLER', 'SBR']
const VERTICAL = ['V89', 'RIGID-PVC-STYLE']
const VERTICAL_LO_ONLY = ['LO89']
const VERTICAL_LO_ONLY_RIGID_PVC = ['LO-RIGID-PVC-STYLE']
const VENETIAN = ['VE25']
const ROLL_EXPRESS = ['ROLLEXP']


const PRODUCT_PROCESS_BLIND_TYPES = [
    ROLLER,
    VERTICAL,
    VERTICAL_LO_ONLY,
    VERTICAL_LO_ONLY_RIGID_PVC,
    VENETIAN,
    ROLL_EXPRESS
]

export {
    ROLLER,
    VERTICAL,
    VERTICAL_LO_ONLY,
    VERTICAL_LO_ONLY_RIGID_PVC,
    VENETIAN,
    ROLL_EXPRESS,
    PRODUCT_PROCESS_BLIND_TYPES
}
